title: Products
sites:
  - en
  - ro
propagate: false
template: default
layout: layout
taxonomies:
  - product_categories
revisions: false
route:
  en: '/products/{slug}'
  ro: '/produse/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
structure:
  root: false
